apiVersion: devops.alauda.io/v1alpha1
kind: PipelineTemplate
metadata:
  name: AlaudaAllInOne
  namespace: default
  annotations:
    alauda.io/displayName.zh-CN: "AlaudaAll-in-one"
    alauda.io/displayName.en: "AlaudaAll-in-one"
    alauda.io/description.zh-CN: "Alauda ACP 2.X All-in-one"
    alauda.io/description.en: "Alauda ACP 2.X All-in-one"
    alauda.io/version: "2.6.8"
    alauda.io/style.icon: golang,docker,sonarqube,kubernetes
  labels:
    category: Build
spec:
  engine: graph
  withSCM: true
  agent:
    label: golang-1.12
  stages:
    - name: All
      tasks:
        - name: alauda-all-in-one
          kind: PipelineTaskTemplate
          type: public/alauda-all-in-one
